// WARNING: This file has been automatically generated by Full Inspector, as part of the serializer
//          selection wizard. It will be overwritten if you change your selected serializers.

#if !(UNITY_4_3 || UNITY_4_5 || UNITY_4_6 || UNITY_5_0 || UNITY_5_3)
namespace FullInspector {
    public abstract class BaseNetworkBehavior : BaseNetworkBehavior<FullInspector.FullSerializerSerializer> {}
}
#endif
